// This file will be auto-generated by Supabase CLI once you have a project.
// Run: supabase gen types typescript --project-id your-project-id > lib/database.types.ts
//
// For now this is a placeholder so the project compiles.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string
          name_fr: string
          name_en: string
          slug: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['categories']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['categories']['Insert']>
      }
      zones: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['zones']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['zones']['Insert']>
      }
      places: {
        Row: {
          id: string
          name: string
          category_id: string | null
          zone_id: string | null
          price_range: 1 | 2 | 3 | null
          description_fr: string | null
          description_en: string | null
          address: string | null
          phone: string | null
          whatsapp: string | null
          hours: PlaceHours | null
          hours_verified_at: string | null
          is_active: boolean
          is_deleted: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['places']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['places']['Insert']>
      }
      photos: {
        Row: {
          id: string
          place_id: string
          storage_path: string
          is_primary: boolean
          is_deleted: boolean
          position: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['photos']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['photos']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          is_admin: boolean
          created_at: string
        }
        Insert: Pick<Database['public']['Tables']['profiles']['Row'], 'id'>
        Update: Pick<Database['public']['Tables']['profiles']['Row'], 'is_admin'>
      }
      favorites: {
        Row: {
          id: string
          user_id: string
          place_id: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['favorites']['Row'], 'id' | 'created_at'>
        Update: never
      }
      weekly_feed: {
        Row: {
          id: string
          week_of: string
          place_id: string
          rank: number
          label_fr: string | null
          label_en: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['weekly_feed']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['weekly_feed']['Insert']>
      }
    }
  }
}

export interface DayHours {
  open: string      // "HH:MM" format e.g. "08:00"
  close: string     // "HH:MM" format e.g. "22:00"
  closed: boolean   // true = closed all day
  overnight: boolean // true = closes after midnight (e.g. bar open until 02:00)
}

export interface PlaceHours {
  mon: DayHours
  tue: DayHours
  wed: DayHours
  thu: DayHours
  fri: DayHours
  sat: DayHours
  sun: DayHours
}
